<?php

declare(strict_types=1);

namespace Database\Seeders;

final class GovernmentHall11Data
{
    public static function companies(): array
    {
        return [
            // Official source: https://momc.gov.sy/en ; current visual references: SANA 2026 information coverage.
            'ministry-information' => ['name'=>'Ministry of Information','sector'=>'government','description'=>'Syrian public institution responsible for information policy, media services, licensing, and official communications.','website'=>'https://momc.gov.sy/en','facebook'=>'https://www.facebook.com/SyrianArabRepublicMinistryOfInformation','year'=>1961,'asset'=>'ministry-information'],
            // Official ministry source: https://dasrfi.moct.gov.sy/ ; current minister reporting: https://sana.sy/en/
            'ministry-communications' => ['name'=>'Ministry of Communications and Information Technology','sector'=>'information_technology','description'=>'Syrian transitional-government ministry responsible for communications, information technology, digital transformation, and national connectivity.','website'=>'https://dasrfi.moct.gov.sy/','facebook'=>'https://www.facebook.com/moctsy','year'=>1961,'asset'=>'ministry-communications'],
            // Official source: https://www.mohesr.gov.sy/ ; cabinet cross-check: https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html
            'ministry-higher-education' => ['name'=>'Ministry of Higher Education and Scientific Research','sector'=>'education','description'=>'Syrian public authority for universities, scientific research, scholarships, and higher-education policy.','website'=>'https://www.mohesr.gov.sy/','facebook'=>'https://www.facebook.com/mohe.gov.sy','year'=>1966,'asset'=>'ministry-higher-education'],
            // Official source: https://www.syrianeducation.org/ ; cabinet cross-check: https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html
            'ministry-education' => ['name'=>'Ministry of Education','sector'=>'education','description'=>'Syrian public authority for school education, curriculum, examinations, and education services.','website'=>'https://www.syrianeducation.org/','facebook'=>'https://www.facebook.com/syrianeducation','year'=>1944,'asset'=>'ministry-education'],
            // Official source: https://www.moh.gov.sy/ ; current health coverage: https://sana.sy/en/health/
            'ministry-health' => ['name'=>'Ministry of Health','sector'=>'healthcare','description'=>'Syrian public institution responsible for public health, hospitals, medical services, and national health programmes.','website'=>'https://www.moh.gov.sy/','facebook'=>'https://www.facebook.com/SyrianMinistryOfHealth','year'=>1961,'asset'=>'ministry-health'],
            // Official source: https://mots.gov.sy/en/ ; current tourism coverage: https://sana.sy/en/
            'ministry-tourism' => ['name'=>'Ministry of Tourism','sector'=>'tourism','description'=>'Syrian public institution responsible for tourism development, heritage destinations, hospitality, and tourism investment.','website'=>'https://mots.gov.sy/en/','facebook'=>'https://www.facebook.com/Syrian.Ministry.of.Tourism','year'=>1966,'asset'=>'ministry-tourism'],
            // Official source: https://www.moc.gov.sy/ ; current culture coverage: https://sana.sy/en/culture-and-arts/
            'ministry-culture' => ['name'=>'Ministry of Culture','sector'=>'culture','description'=>'Syrian public institution responsible for cultural policy, heritage, arts, publishing, and cultural programmes.','website'=>'https://www.moc.gov.sy/','facebook'=>'https://www.facebook.com/SyrianMinistryofCulture','year'=>1958,'asset'=>'ministry-culture'],
            // Current cabinet cross-check: https://en.wikipedia.org/wiki/Cabinet_of_Syria ; current minister coverage: https://sana.sy/en/
            'ministry-economy' => ['name'=>'Ministry of Economy and Foreign Trade','sector'=>'government','description'=>'Syrian public institution responsible for economic policy, foreign trade, investment coordination, and market development.','website'=>'https://www.syrecon.org/','facebook'=>'https://www.facebook.com/SyrianEconomyMinistry','year'=>1961,'asset'=>'ministry-economy'],
            // Current cabinet cross-check: https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html ; Ministry/Economy reporting: https://sana.sy/en/
            'ministry-industry' => ['name'=>'Ministry of Industry','sector'=>'industrial','description'=>'Syrian public institution responsible for industrial development, public industrial enterprises, and manufacturing policy.','website'=>'https://www.moid.gov.sy/','facebook'=>'https://www.facebook.com/SyrianIndustryMinistry','year'=>1961,'asset'=>'ministry-industry'],
            // Official current minister source: https://sana.sy/en/presidency/2315736/
            'ministry-agriculture' => ['name'=>'Ministry of Agriculture and Agrarian Reform','sector'=>'agriculture','description'=>'Syrian public institution responsible for agriculture, irrigation coordination, livestock, food security, and rural development.','website'=>'https://sana.sy/en/presidency/2315736/','facebook'=>'https://www.facebook.com/SyrianMinistryofAgriculture','year'=>1961,'asset'=>'ministry-agriculture'],
            // Official source directory: https://psc.gov.sy/site2/links-EN.htm ; current transport reporting: https://sana.sy/en/
            'ministry-transport' => ['name'=>'Ministry of Transport','sector'=>'transportation_logistics','description'=>'Syrian public institution responsible for transport policy, roads, ports, aviation, and logistics infrastructure.','website'=>'https://www.mot.gov.sy/','facebook'=>'https://www.facebook.com/SyrianMinistryOfTransport','year'=>1961,'asset'=>'ministry-transport'],
            // Updated post-2025 identity: https://commons.wikimedia.org/wiki/File:Syrian_Ministry_of_Energy_logo_(2025).png ; current energy reporting: https://sana.sy/en/
            'ministry-electricity' => ['name'=>'Ministry of Energy','sector'=>'government','description'=>'Current Syrian transitional-government ministry responsible for electricity, generation, transmission, distribution, energy recovery, and renewable-energy coordination.','website'=>'https://moe.gov.sy/','facebook'=>'https://www.facebook.com/moe.gov.sy','year'=>1961,'asset'=>'ministry-electricity'],
            // Official source: https://www.mof.gov.sy/ ; current finance minister reporting: https://sana.sy/en/
            'ministry-finance' => ['name'=>'Ministry of Finance','sector'=>'finance','description'=>'Syrian public institution responsible for public finance, budgeting, treasury, and fiscal administration.','website'=>'https://www.mof.gov.sy/','facebook'=>'https://www.facebook.com/SyrianMinistryOfFinance','year'=>1961,'asset'=>'ministry-finance'],
            // Official source: https://www.mola.gov.sy/ ; current municipal coverage: https://sana.sy/en/
            'ministry-local-admin' => ['name'=>'Ministry of Local Administration and Environment','sector'=>'government','description'=>'Syrian public institution responsible for local government, municipalities, environmental administration, and local development.','website'=>'https://www.mola.gov.sy/','facebook'=>'https://www.facebook.com/SyrianMinistryLocalAdministration','year'=>1971,'asset'=>'ministry-local-admin'],
            // Current minister source: https://sana.sy/en/ ; current strategy reporting: https://sana.sy/en/
            'ministry-social-affairs' => ['name'=>'Ministry of Social Affairs and Labour','sector'=>'social_development','description'=>'Syrian public institution responsible for social protection, labour policy, disability inclusion, and social development.','website'=>'https://www.mosal.gov.sy/','facebook'=>'https://www.facebook.com/SyrianMinistrySocialAffairs','year'=>1961,'asset'=>'ministry-social-affairs'],
            // Official professional source: https://www.linkedin.com/company/siasyria ; World Bank source: https://www.worldbank.org/en/events/2026/03/24/focused-exchange-with-talal-al-hilali-syrian-head-of-investment-authority-french-c
            'syrian-investment-authority' => ['name'=>'Syrian Investment Authority','sector'=>'government','description'=>'National gateway for investment in Syria, supporting strategic projects, investment services, and investor coordination.','website'=>'https://sia.gov.sy/','linkedin'=>'https://www.linkedin.com/company/siasyria','year'=>2007,'asset'=>'syrian-investment-authority'],
            // Current defense reporting: https://sana.sy/en/ ; cabinet cross-check: https://en.wikipedia.org/wiki/Cabinet_of_Syria
            'ministry-defense' => ['name'=>'Ministry of Defense','sector'=>'government','description'=>'Syrian public institution responsible for national defense administration and defense-sector coordination.','website'=>'https://sana.sy/en/','facebook'=>'https://www.facebook.com/SyrianMinistryOfDefense','year'=>1946,'asset'=>'ministry-defense'],
            // Current Parliament sources: SANA Speaker profile https://sana.sy/en/syria/2329045/ ; IPU profile https://data.ipu.org/parliament/SY/SY-LC01/ ; current member list https://en.wikipedia.org/wiki/List_of_members_of_the_People%27s_Assembly_(Syria),_2026%E2%80%93present.
            'peoples-assembly' => ['name'=>'People\'s Assembly of the Syrian Arab Republic','sector'=>'government','description'=>'The current unicameral Syrian People\'s Assembly (Majlis Al-Chaab), the transitional legislature for the 2026–2029 term.','website'=>'https://data.ipu.org/parliament/SY/SY-LC01/','facebook'=>'https://www.facebook.com/SyrianArabRepublicPeopleAssembly','year'=>2026,'asset'=>'peoples-assembly'],
        ];
    }

    public static function people(): array
    {
        return [
            // Official portrait and biography: https://sana.sy/en/presidency/2315733/
            ['key'=>'khaled-fawaz-zaarour','companies'=>['ministry-information'],'name'=>'Khaled Fawaz Zaarour','email'=>'khaled.zaarour@government-hall11.test','role'=>'Minister of Information','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Khaled%20Fawaz%20Zaarour','source'=>'https://sana.sy/en/presidency/2315733/','asset'=>'khaled-fawaz-zaarour'],
            // Official portrait and biography: https://sana.sy/en/presidency/2315736/
            ['key'=>'basel-hafez-al-suwaidan','companies'=>['ministry-agriculture'],'name'=>'Basel Hafez al-Suwaidan','email'=>'basel.suwaidan@government-hall11.test','role'=>'Minister of Agriculture','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Basel%20Hafez%20al-Suwaidan','source'=>'https://sana.sy/en/presidency/2315736/','asset'=>'basel-hafez-al-suwaidan'],
            // Current cabinet source: https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html ; portrait source: SANA current social-affairs coverage.
            ['key'=>'hind-kabawat','companies'=>['ministry-social-affairs'],'name'=>'Hind Kabawat','email'=>'hind.kabawat@government-hall11.test','role'=>'Minister of Social Affairs and Labour','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Hind%20Kabawat','source'=>'https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html','asset'=>'hind-kabawat'],
            // Current cabinet source: https://en.wikipedia.org/wiki/Cabinet_of_Syria ; portrait source: SANA defense coverage.
            ['key'=>'murhaf-abu-qasra','companies'=>['ministry-defense'],'name'=>'Murhaf Abu Qasra','email'=>'murhaf.abuqasra@government-hall11.test','role'=>'Minister of Defense','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Murhaf%20Abu%20Qasra','source'=>'https://en.wikipedia.org/wiki/Cabinet_of_Syria','asset'=>'murhaf-abu-qasra'],
            // World Bank profile/event source: https://www.worldbank.org/en/events/2026/03/24/focused-exchange-with-talal-al-hilali-syrian-head-of-investment-authority-french-c
            ['key'=>'talal-al-hilali','companies'=>['syrian-investment-authority'],'name'=>'Talal al-Hilali','email'=>'talal.hilali@government-hall11.test','role'=>'Director General of the Syrian Investment Authority','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Talal%20al-Hilali','source'=>'https://www.worldbank.org/en/events/2026/03/24/focused-exchange-with-talal-al-hilali-syrian-head-of-investment-authority-french-c','asset'=>'talal-al-hilali'],
            // Current cabinet source: https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html ; current minister coverage: https://sana.sy/en/
            ['key'=>'abdul-salam-haykal','companies'=>['ministry-communications'],'name'=>'Abdul-Salam Haykal','email'=>'abdul.salam.haykal@government-hall11.test','role'=>'Minister of Communications and Information Technology','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Abdul-Salam%20Haykal','source'=>'https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html','asset'=>'abdul-salam-haykal'],
            // Current cabinet source: https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html ; minister coverage: https://sana.sy/en/
            ['key'=>'mohammad-nidal-al-shaar','companies'=>['ministry-economy','ministry-industry'],'name'=>'Mohammad Nidal al-Shaar','email'=>'mohammad.nidal.alshaar@government-hall11.test','role'=>'Minister of Economy and Industry','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Mohammad%20Nidal%20al-Shaar','source'=>'https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html','asset'=>'mohammad-nidal-al-shaar'],
            // Current cabinet source: https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html ; SANA ministry source: https://sana.sy/en/
            ['key'=>'musab-nazal-al-ali','companies'=>['ministry-local-admin'],'name'=>'Musab Nazal al-Ali','email'=>'musab.nazal.ali@government-hall11.test','role'=>'Minister of Local Administration and Environment','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Musab%20Nazal%20al-Ali','source'=>'https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html','asset'=>'musab-nazal-al-ali'],
            // Current cabinet source: https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html ; education reporting: https://sana.sy/en/
            ['key'=>'mohammad-hassan-al-skaff','companies'=>['ministry-education'],'name'=>'Mohammad Hassan al-Skaff','email'=>'mohammad.hassan.skaff@government-hall11.test','role'=>'Minister of Education','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Mohammad%20Hassan%20al-Skaff','source'=>'https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html','asset'=>'mohammad-hassan-al-skaff'],
            // Current cabinet source: https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html ; health reporting: https://sana.sy/en/health/
            ['key'=>'mohammad-anjarani','companies'=>['ministry-health'],'name'=>'Mohammad Anjarani','email'=>'mohammad.anjarani@government-hall11.test','role'=>'Minister of Health','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Mohammad%20Anjarani','source'=>'https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html','asset'=>'mohammad-anjarani'],
            // Current cabinet source: https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html ; higher-education reporting: https://sana.sy/en/
            ['key'=>'mustafa-abd-al-razzaq','companies'=>['ministry-higher-education'],'name'=>'Mustafa Abd al-Razzaq','email'=>'mustafa.abd.alrazzaq@government-hall11.test','role'=>'Minister of Higher Education and Scientific Research','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Mustafa%20Abd%20al-Razzaq','source'=>'https://karamshaar.com/wp-content/themes/karam-shaar-theme/assets/charts/Syrian-Interim-Government.html','asset'=>'mustafa-abd-al-razzaq'],
            // Current finance reporting: https://sana.sy/en/ ; cabinet cross-check: https://en.wikipedia.org/wiki/Cabinet_of_Syria
            ['key'=>'mohammad-yaser-bernieh','companies'=>['ministry-finance'],'name'=>'Mohammad Yaser Bernieh','email'=>'mohammad.yaser.bernieh@government-hall11.test','role'=>'Minister of Finance','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Mohammad%20Yaser%20Bernieh','source'=>'https://en.wikipedia.org/wiki/Cabinet_of_Syria','asset'=>'mohammad-yaser-bernieh'],
            // Current tourism coverage: https://mots.gov.sy/en/ ; SANA tourism reporting: https://sana.sy/en/
            ['key'=>'mazen-al-salhani','companies'=>['ministry-tourism'],'name'=>'Mazen al-Salhani','email'=>'mazen.al.salhani@government-hall11.test','role'=>'Minister of Tourism','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Mazen%20al-Salhani','source'=>'https://mots.gov.sy/en/','asset'=>'mazen-al-salhani'],
            // Current culture coverage: https://sana.sy/en/culture-and-arts/
            ['key'=>'mohammad-yasin-saleh','companies'=>['ministry-culture'],'name'=>'Mohammad Yasin Saleh','email'=>'mohammad.yasin.saleh@government-hall11.test','role'=>'Minister of Culture','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Mohammad%20Yasin%20Saleh','source'=>'https://sana.sy/en/culture-and-arts/','asset'=>'mohammad-yasin-saleh'],
            // Current transport coverage: https://sana.sy/en/
            ['key'=>'yarub-suleiman-badr','companies'=>['ministry-transport'],'name'=>'Yarub Suleiman Badr','email'=>'yarub.suleiman.badr@government-hall11.test','role'=>'Minister of Transport','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Yarub%20Suleiman%20Badr','source'=>'https://en.wikipedia.org/wiki/Cabinet_of_Syria','asset'=>'yarub-suleiman-badr'],
            // Current energy coverage: https://sana.sy/en/
            ['key'=>'mohammad-al-bashir','companies'=>['ministry-electricity'],'name'=>'Mohammad al-Bashir','email'=>'mohammad.albashir@government-hall11.test','role'=>'Minister of Energy','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Mohammad%20al-Bashir%20Syria','source'=>'https://sana.sy/en/','asset'=>'mohammad-al-bashir'],
            // Deputy Defense Minister source: https://sana.sy/en/syria/2262740/ ; current Defense coverage is also cross-checked via SANA.
            ['key'=>'fahim-issa','companies'=>['ministry-defense'],'name'=>'Fahim Issa','email'=>'fahim.issa@government-hall11.test','role'=>'Deputy Minister of Defense for the Northern Region','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Fahim%20Issa%20Syria','source'=>'https://sana.sy/en/syria/2262740/','asset'=>'fahim-issa'],
            // Chief of Staff source: current SANA reporting on Ali al-Nassan: https://sana.sy/en/
            ['key'=>'ali-al-nassan','companies'=>['ministry-defense'],'name'=>'Ali al-Nassan','email'=>'ali.alnassan@government-hall11.test','role'=>'Chief of Staff of the Syrian Army','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Ali%20al-Nassan%20Syria','source'=>'https://sana.sy/en/','asset'=>'ali-al-nassan'],
            // Official Ministry of Culture source: https://moc.gov.sy/en/news ; current minister source: https://sana.sy/en/culture-and-arts/2331391/
            ['key'=>'saad-naasan','companies'=>['ministry-culture'],'name'=>'Saad Naasan','email'=>'saad.naasan@government-hall11.test','role'=>'Deputy Minister of Culture','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Saad%20Naasan%20Syria','source'=>'https://moc.gov.sy/en/news','asset'=>'saad-naasan'],
            // SANA communications agreement source naming the Director General: https://sana.sy/en/economic/2263327/
            ['key'=>'jamal-al-din-khatib','companies'=>['ministry-communications'],'name'=>'Jamal Al-Din Khatib','email'=>'jamal.khatib@government-hall11.test','role'=>'Director General of the Syrian Telecommunications Establishment','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Jamaleddin%20Khatib%20Syrian%20Telecom','source'=>'https://sana.sy/en/economic/2263327/','asset'=>'jamal-al-din-khatib'],
            // Parliament member list and SANA leadership report: https://en.wikipedia.org/wiki/List_of_members_of_the_People%27s_Assembly_(Syria),_2026%E2%80%93present ; https://sana.sy/en/syria/2329045/
            ['key'=>'abdul-hamid-al-awak','companies'=>['peoples-assembly'],'name'=>'Abdul Hamid Akil al-Awak','email'=>'abdul.hamid.alawak@government-hall11.test','role'=>'Speaker of the People\'s Assembly','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Abdul%20Hamid%20al-Awak','source'=>'https://sana.sy/en/syria/2329045/','asset'=>'abdul-hamid-al-awak'],
            ['key'=>'mustafa-al-mousa','companies'=>['peoples-assembly'],'name'=>'Mustafa al-Mousa','email'=>'mustafa.al.mousa@government-hall11.test','role'=>'First Deputy Speaker of the People\'s Assembly','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Mustafa%20al-Mousa%20Syria','source'=>'https://en.wikipedia.org/wiki/List_of_members_of_the_People%27s_Assembly_(Syria),_2026%E2%80%93present','asset'=>'mustafa-al-mousa'],
            ['key'=>'madonna-bishara','companies'=>['peoples-assembly'],'name'=>'Madonna Bishara','email'=>'madonna.bishara@government-hall11.test','role'=>'Second Deputy Speaker of the People\'s Assembly','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Madonna%20Bishara%20Syria','source'=>'https://en.wikipedia.org/wiki/List_of_members_of_the_People%27s_Assembly_(Syria),_2026%E2%80%93present','asset'=>'madonna-bishara'],
            ['key'=>'gabriel-moushe-gawrieh','companies'=>['peoples-assembly'],'name'=>'Gabriel Moushe Gawrieh','email'=>'gabriel.gawrieh@government-hall11.test','role'=>'Member of the People\'s Assembly; Assyrian Democratic Organisation representative','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Gabriel%20Moushe%20Gawrieh','source'=>'https://en.wikipedia.org/wiki/List_of_members_of_the_People%27s_Assembly_(Syria),_2026%E2%80%93present','asset'=>'gabriel-moushe-gawrieh'],
            ['key'=>'azzam-fadhel-khanji','companies'=>['peoples-assembly'],'name'=>'Azzam Fadhel Khanji','email'=>'azzam.khanji@government-hall11.test','role'=>'Member of the People\'s Assembly','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Azzam%20Fadhel%20Khanji','source'=>'https://en.wikipedia.org/wiki/List_of_members_of_the_People%27s_Assembly_(Syria),_2026%E2%80%93present','asset'=>'azzam-fadhel-khanji'],
            ['key'=>'mouayad-ghazlan-al-qablawi','companies'=>['peoples-assembly'],'name'=>'Mouayad Ghazlan al-Qablawi','email'=>'mouayad.qablawi@government-hall11.test','role'=>'Member of the People\'s Assembly; former Speaker candidate','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Mouayad%20Ghazlan%20al-Qablawi','source'=>'https://sana.sy/en/syria/2329045/','asset'=>'mouayad-ghazlan-al-qablawi'],
            ['key'=>'osama-al-assaf','companies'=>['peoples-assembly'],'name'=>'Osama al-Assaf','email'=>'osama.alassaf@government-hall11.test','role'=>'Member of the People\'s Assembly; oldest member chairing the inaugural session','linkedin'=>'https://www.linkedin.com/search/results/people/?keywords=Osama%20al-Assaf%20Syria','source'=>'https://en.wikipedia.org/wiki/List_of_members_of_the_People%27s_Assembly_(Syria),_2026%E2%80%93present','asset'=>'osama-al-assaf'],
        ];
    }
}
