<?php

declare(strict_types=1);

namespace Database\Seeders\RealData;

final class FilteredConnectionUsersData
{
    public static function users(): array
    {
        return [
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Sami+Almouradi
            ['slug' => 'sami-almouradi', 'first_name' => 'Sami', 'last_name' => 'Almouradi', 'email' => 'sami-almouradi@approved-users.test', 'phone' => '+963-912-620-112', 'location' => 'Syria,Damascus', 'job' => 'AI, ICPC and TEDx community professional', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Sami+Almouradi'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Farah+Alsaleem
            ['slug' => 'farah-alsaleem', 'first_name' => 'Farah', 'last_name' => 'Alsaleem', 'email' => 'farah-alsaleem@approved-users.test', 'phone' => '+963-914-620-114', 'location' => 'Syria,Damascus', 'job' => 'Senior Full-Stack Developer', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Farah+Alsaleem'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Joud+Khattab
            ['slug' => 'joud-khattab', 'first_name' => 'Joud', 'last_name' => 'Khattab', 'email' => 'joud-khattab@approved-users.test', 'phone' => '+963-916-620-116', 'location' => 'Syria,Damascus', 'job' => 'Data and Information Management professional', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Joud+Khattab'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Tasneem+Almunajjed
            ['slug' => 'tasneem-almunajjed', 'first_name' => 'Tasneem', 'last_name' => 'Almunajjed', 'email' => 'tasneem-almunajjed@approved-users.test', 'phone' => '+963-918-620-118', 'location' => 'Syria,Damascus', 'job' => 'Cybersecurity and ICPC participant', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Tasneem+Almunajjed'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Kareem+Bizreh
            ['slug' => 'kareem-bizreh', 'first_name' => 'Kareem', 'last_name' => 'Bizreh', 'email' => 'kareem-bizreh@approved-users.test', 'phone' => '+963-920-620-120', 'location' => 'Syria,Damascus', 'job' => 'Frontend and ICPC professional', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Kareem+Bizreh'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Ahmad+Al-Sultan
            ['slug' => 'ahmad-al-sultan', 'first_name' => 'Ahmad', 'last_name' => 'Al-Sultan', 'email' => 'ahmad-al-sultan@approved-users.test', 'phone' => '+963-922-620-122', 'location' => 'Syria,Damascus', 'job' => 'Senior Software Engineer', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Ahmad+Al-Sultan'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Amjad+Ghneim
            ['slug' => 'amjad-ghneim', 'first_name' => 'Amjad', 'last_name' => 'Ghneim', 'email' => 'amjad-ghneim@approved-users.test', 'phone' => '+963-924-620-124', 'location' => 'Syria,Damascus', 'job' => 'Full-Stack Engineer and Engineering Management', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Amjad+Ghneim'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Sana+Hawasly
            ['slug' => 'sana-hawasly', 'first_name' => 'Sana', 'last_name' => 'Hawasly', 'email' => 'sana-hawasly@approved-users.test', 'phone' => '+963-926-620-126', 'location' => 'Syria,Damascus', 'job' => 'EdTech, STEM and community building', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Sana+Hawasly'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Amr+Alsaleh
            ['slug' => 'amr-alsaleh', 'first_name' => 'Amr', 'last_name' => 'Alsaleh', 'email' => 'amr-alsaleh@approved-users.test', 'phone' => '+963-928-620-128', 'location' => 'Syria,Damascus', 'job' => 'Systems and Software Engineering', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Amr+Alsaleh'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Omar+Omarain
            ['slug' => 'omar-omarain', 'first_name' => 'Omar', 'last_name' => 'Omarain', 'email' => 'omar-omarain@approved-users.test', 'phone' => '+963-930-620-130', 'location' => 'Syria,Damascus', 'job' => 'Product-focused Software Engineer', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Omar+Omarain'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Amjad+Alhaffar
            ['slug' => 'amjad-alhaffar', 'first_name' => 'Amjad', 'last_name' => 'Alhaffar', 'email' => 'amjad-alhaffar@approved-users.test', 'phone' => '+963-932-620-132', 'location' => 'Syria,Damascus', 'job' => 'Software Engineering and AI', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Amjad+Alhaffar'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Sara+Kataf
            ['slug' => 'sara-kataf', 'first_name' => 'Sara', 'last_name' => 'Kataf', 'email' => 'sara-kataf@approved-users.test', 'phone' => '+963-934-620-134', 'location' => 'Syria,Damascus', 'job' => 'CMO and Co-Founder; startup mentor', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Sara+Kataf'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Mohamed+Ghazal
            ['slug' => 'mohamed-ghazal', 'first_name' => 'Mohamed', 'last_name' => 'Ghazal', 'email' => 'mohamed-ghazal@approved-users.test', 'phone' => '+963-936-620-136', 'location' => 'Syria,Damascus', 'job' => 'Executive Director; startup ecosystem and VC', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Mohamed+Ghazal'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Ayman+Hasan
            ['slug' => 'ayman-hasan', 'first_name' => 'Ayman', 'last_name' => 'Hasan', 'email' => 'ayman-hasan@approved-users.test', 'phone' => '+963-938-620-138', 'location' => 'Syria,Damascus', 'job' => 'Founder and CEO at Reybill', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Ayman+Hasan'],
            // LinkedIn: https://www.linkedin.com/in/ghalia-alshamaa-47ab9b3b2/
            ['slug' => 'ghalia-alshamaa', 'first_name' => 'Ghalia', 'last_name' => 'Alshamaa', 'email' => 'ghalia-alshamaa@approved-users.test', 'phone' => '+963-940-620-140', 'location' => 'Syria,Damascus', 'job' => 'ITE Student | learning Web Development | Java & C++ | Object-Oriented Programming | Problem Solving', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/ghalia-alshamaa-47ab9b3b2/'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Aya+Khrnoub
            ['slug' => 'aya-khrnoub', 'first_name' => 'Aya', 'last_name' => 'Khrnoub', 'email' => 'aya-khrnoub@approved-users.test', 'phone' => '+963-942-620-142', 'location' => 'Syria,Damascus', 'job' => 'Project Manager and Product Owner at IXCoders', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Aya+Khrnoub'],
            // LinkedIn: https://www.linkedin.com/in/mohamad-alarnous-b2b4b6255/
            ['slug' => 'mohamad-alarnous', 'first_name' => 'Mohamad', 'last_name' => 'Alarnous', 'email' => 'mohamad-alarnous@approved-users.test', 'phone' => '+963-944-620-144', 'location' => 'Syria,Damascus', 'job' => 'Software Engineer', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/mohamad-alarnous-b2b4b6255/'],
            // LinkedIn: https://www.linkedin.com/in/joud-mrad-060514421/
            ['slug' => 'joud-mrad', 'first_name' => 'Joud', 'last_name' => 'Mrad', 'email' => 'joud-mrad@approved-users.test', 'phone' => '+963-946-620-146', 'location' => 'Syria,Damascus', 'job' => 'Full-Stack Software Engineer | Flutter and React Developer | Practical Instructor at Damascus University | Master’s Student | Data Governance Intern at Syriatel (DBA)', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/joud-mrad-060514421/'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=عمر+كحيل
            ['slug' => 'omar-kahil', 'first_name' => 'Omar', 'last_name' => 'Kahil', 'email' => 'omar-kahil@approved-users.test', 'phone' => '+963-948-620-148', 'location' => 'Syria,Damascus', 'job' => 'Full-Stack Engineer; NestJS and Flutter', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=عمر+كحيل'],
            // LinkedIn: https://www.linkedin.com/in/tariqodeh-dev/
            ['slug' => 'tariq-odeh', 'first_name' => 'Tariq', 'last_name' => 'Odeh', 'email' => 'tariq-odeh@approved-users.test', 'phone' => '+963-950-620-150', 'location' => 'Syria,Damascus', 'job' => 'Backend Developer | Laravel', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/tariqodeh-dev/'],
            // LinkedIn: https://www.linkedin.com/in/aya-aljamal-905277417/
            ['slug' => 'aya-aljamal', 'first_name' => 'Aya', 'last_name' => 'Aljamal', 'email' => 'aya-aljamal@approved-users.test', 'phone' => '+963-952-620-152', 'location' => 'Syria,Damascus', 'job' => 'IT Engineering Student | Passionate about Software Development & Problem Solving | Aspiring Tech Innovator', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/aya-aljamal-905277417/'],
            // LinkedIn: https://www.linkedin.com/in/mohamed-al-aeinia-263428261/
            ['slug' => 'mohamed-al-aeinia', 'first_name' => 'Mohamed', 'last_name' => 'Al-aeinia', 'email' => 'mohamed-al-aeinia@approved-users.test', 'phone' => '+963-954-620-154', 'location' => 'Syria,Damascus', 'job' => 'AI Engineer | AI Automation, LLM Fine-Tuning & NLP | Competitive Programmer', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/mohamed-al-aeinia-263428261/'],
            // LinkedIn: https://www.linkedin.com/in/mariamalsarmany/
            ['slug' => 'mariam-alsarmany', 'first_name' => 'Mariam', 'last_name' => 'Alsarmany', 'email' => 'mariam-alsarmany@approved-users.test', 'phone' => '+963-956-620-156', 'location' => 'Syria,Damascus', 'job' => 'Creative Art Director | Media Manager | Video Specialist | Copywriter & Trainer', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/mariamalsarmany/'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Mohammed+Ayyash
            ['slug' => 'mohammed-ayyash', 'first_name' => 'Mohammed', 'last_name' => 'Ayyash', 'email' => 'mohammed-ayyash@approved-users.test', 'phone' => '+963-958-620-158', 'location' => 'Syria,Damascus', 'job' => 'HR Consultant and Professional Trainer', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Mohammed+Ayyash'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Abdelrahman+Saleh
            ['slug' => 'abdelrahman-saleh', 'first_name' => 'Abdelrahman', 'last_name' => 'Saleh', 'email' => 'abdelrahman-saleh@approved-users.test', 'phone' => '+963-960-620-160', 'location' => 'Syria,Damascus', 'job' => 'ICT Teacher', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Abdelrahman+Saleh'],
            // LinkedIn: https://www.linkedin.com/in/rawan-almasri-sw/
            ['slug' => 'rawan-almasri', 'first_name' => 'Rawan', 'last_name' => 'Almasri', 'email' => 'rawan-almasri@approved-users.test', 'phone' => '+963-9140-620-240', 'location' => 'Syria,Damascus', 'job' => 'Software Engineer | Master’s Degree Student in Information Systems | Full Stack Mobile Developer (Flutter, Node.js, Express.js, NestJS) | SQL DB Engineer | SCPC Organizer', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/rawan-almasri-sw/'],
            // LinkedIn: https://www.linkedin.com/in/sedra-nadr-a16082324/
            ['slug' => 'sedra-nadr', 'first_name' => 'Sedra', 'last_name' => 'Nadr', 'email' => 'sedra-nadr@approved-users.test', 'phone' => '+963-9142-620-242', 'location' => 'Syria,Damascus', 'job' => 'Software Engineer', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/sedra-nadr-a16082324/'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Marah+Aljumaat
            ['slug' => 'marah-aljumaat', 'first_name' => 'Marah', 'last_name' => 'Aljumaat', 'email' => 'marah-aljumaat@approved-users.test', 'phone' => '+963-966-620-166', 'location' => 'Syria,Damascus', 'job' => 'University student', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Marah+Aljumaat'],
            // LinkedIn: https://www.linkedin.com/in/yehya-msouty-03a670318/
            ['slug' => 'yehya-msouty', 'first_name' => 'Yehya', 'last_name' => 'Msouty', 'email' => 'yehya-msouty@approved-users.test', 'phone' => '+963-968-620-168', 'location' => 'Syria,Damascus', 'job' => 'Contestant, Judge and Problem-setter | Aleppo University', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/yehya-msouty-03a670318/'],
            // LinkedIn: https://www.linkedin.com/in/khaled-tamim-802543314/
            ['slug' => 'khaled-tamim', 'first_name' => 'Khaled', 'last_name' => 'Tamim', 'email' => 'khaled-tamim@approved-users.test', 'phone' => '+963-970-620-170', 'location' => 'Syria,Damascus', 'job' => 'Fourth-year Information Technology student at Damascus University specializing in Artificial Intelligence', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/khaled-tamim-802543314/'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Majd+Alhariri
            ['slug' => 'majd-alhariri', 'first_name' => 'Majd', 'last_name' => 'Alhariri', 'email' => 'majd-alhariri@approved-users.test', 'phone' => '+963-972-620-172', 'location' => 'Syria,Damascus', 'job' => 'Technology professional from Daraa', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Majd+Alhariri'],
            // LinkedIn: https://www.linkedin.com/in/muhammed-mubaker/
            ['slug' => 'muhammed-mubaker', 'first_name' => 'Muhammed', 'last_name' => 'Mubaker', 'email' => 'muhammed-mubaker@approved-users.test', 'phone' => '+963-974-620-174', 'location' => 'Syria,Damascus', 'job' => 'Computer Engineer || Backend Specialist @ DealGo', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/muhammed-mubaker/'],
            // LinkedIn: https://www.linkedin.com/in/nour-rajab-766b983a3/
            ['slug' => 'nour-rajab', 'first_name' => 'Nour', 'last_name' => 'Rajab', 'email' => 'nour-rajab@approved-users.test', 'phone' => '+963-9144-620-244', 'location' => 'Syria,Damascus', 'job' => 'IT Engineering Student | Building Programming Foundations | Eager to Learn & Grow', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/nour-rajab-766b983a3/'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Ayman+Durra
            ['slug' => 'ayman-durra', 'first_name' => 'Ayman', 'last_name' => 'Durra', 'email' => 'ayman-durra@approved-users.test', 'phone' => '+963-978-620-178', 'location' => 'Syria,Damascus', 'job' => 'Software Engineer', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Ayman+Durra'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Ghufran+Sbiai
            ['slug' => 'ghufran-sbiai', 'first_name' => 'Ghufran', 'last_name' => 'Sbiai', 'email' => 'ghufran-sbiai@approved-users.test', 'phone' => '+963-980-620-180', 'location' => 'Syria,Damascus', 'job' => 'Telecommunications Engineer', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Ghufran+Sbiai'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Albatool+Saramejo
            ['slug' => 'albatool-saramejo', 'first_name' => 'Albatool', 'last_name' => 'Saramejo', 'email' => 'albatool-saramejo@approved-users.test', 'phone' => '+963-982-620-182', 'location' => 'Syria,Damascus', 'job' => 'Software Engineering and technology', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Albatool+Saramejo'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Abdulmalek+Rajab
            ['slug' => 'abdulmalek-rajab', 'first_name' => 'Abdulmalek', 'last_name' => 'Rajab', 'email' => 'abdulmalek-rajab@approved-users.test', 'phone' => '+963-984-620-184', 'location' => 'Syria,Damascus', 'job' => 'Software Engineer at 88ninety', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Abdulmalek+Rajab'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Motaz+Al+Masri
            ['slug' => 'motaz-al-masri', 'first_name' => 'Motaz', 'last_name' => 'Al Masri', 'email' => 'motaz-al-masri@approved-users.test', 'phone' => '+963-986-620-186', 'location' => 'Syria,Damascus', 'job' => 'Backend Developer; Laravel and REST APIs', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Motaz+Al+Masri'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Ghaith+AlHallak
            ['slug' => 'ghaith-alhallak', 'first_name' => 'Ghaith', 'last_name' => 'AlHallak', 'email' => 'ghaith-alhallak@approved-users.test', 'phone' => '+963-988-620-188', 'location' => 'Syria,Damascus', 'job' => 'Software Engineer; Full-Stack and Applied AI', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Ghaith+AlHallak'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Yasmeen+Al+rajleh
            ['slug' => 'yasmeen-al-rajleh', 'first_name' => 'Yasmeen', 'last_name' => 'Al rajleh', 'email' => 'yasmeen-al-rajleh@approved-users.test', 'phone' => '+963-990-620-190', 'location' => 'Syria,Damascus', 'job' => 'Al-Khawarizmi Fellowship participant', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Yasmeen+Al+rajleh'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Mohamad+Fadi+Kaso
            ['slug' => 'mohamad-fadi-kaso', 'first_name' => 'Mohamad', 'last_name' => 'Fadi Kaso', 'email' => 'mohamad-fadi-kaso@approved-users.test', 'phone' => '+963-992-620-192', 'location' => 'Syria,Damascus', 'job' => 'IT Engineer', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Mohamad+Fadi+Kaso'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Mohamed+Anas+Abo+Alzahab
            ['slug' => 'mohamed-anas-abo-alzahab', 'first_name' => 'Mohamed', 'last_name' => 'Anas Abo Alzahab', 'email' => 'mohamed-anas-abo-alzahab@approved-users.test', 'phone' => '+963-994-620-194', 'location' => 'Syria,Damascus', 'job' => 'IT and AI Engineering; Backend', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Mohamed+Anas+Abo+Alzahab'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Mahmoud+Matrawy
            ['slug' => 'mahmoud-matrawy', 'first_name' => 'Mahmoud', 'last_name' => 'Matrawy', 'email' => 'mahmoud-matrawy@approved-users.test', 'phone' => '+963-996-620-196', 'location' => 'Syria,Damascus', 'job' => 'Founder and CEO at Elenex', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Mahmoud+Matrawy'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Aya+Mahbob+Alhara
            ['slug' => 'aya-mahbob-alhara', 'first_name' => 'Aya', 'last_name' => 'Mahbob Alhara', 'email' => 'aya-mahbob-alhara@approved-users.test', 'phone' => '+963-998-620-198', 'location' => 'Syria,Damascus', 'job' => 'Software Engineering and Backend Development', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Aya+Mahbob+Alhara'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Mohammad+Suleman
            ['slug' => 'mohammad-suleman', 'first_name' => 'Mohammad', 'last_name' => 'Suleman', 'email' => 'mohammad-suleman@approved-users.test', 'phone' => '+963-9100-620-200', 'location' => 'Syria,Damascus', 'job' => 'Cloud and Automation', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Mohammad+Suleman'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Sidra+Atiya
            ['slug' => 'sidra-atiya', 'first_name' => 'Sidra', 'last_name' => 'Atiya', 'email' => 'sidra-atiya@approved-users.test', 'phone' => '+963-9102-620-202', 'location' => 'Syria,Damascus', 'job' => 'Computer Science and Backend Development', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Sidra+Atiya'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Tala+Hallak
            ['slug' => 'tala-hallak', 'first_name' => 'Tala', 'last_name' => 'Hallak', 'email' => 'tala-hallak@approved-users.test', 'phone' => '+963-9104-620-204', 'location' => 'Syria,Damascus', 'job' => 'Information Technology Engineering', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Tala+Hallak'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Rowan+Al+Sheikh+Ali
            ['slug' => 'rowan-al-sheikh-ali', 'first_name' => 'Rowan', 'last_name' => 'Al Sheikh Ali', 'email' => 'rowan-al-sheikh-ali@approved-users.test', 'phone' => '+963-9106-620-206', 'location' => 'Syria,Damascus', 'job' => 'IT Engineering and Cybersecurity', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Rowan+Al+Sheikh+Ali'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Amjad+Al+Barazi
            ['slug' => 'amjad-al-barazi', 'first_name' => 'Amjad', 'last_name' => 'Al Barazi', 'email' => 'amjad-al-barazi@approved-users.test', 'phone' => '+963-9108-620-208', 'location' => 'Syria,Damascus', 'job' => 'Product Manager and Digital Products', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Amjad+Al+Barazi'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Mhamad+Hamza+Alattar
            ['slug' => 'mhamad-hamza-alattar', 'first_name' => 'Mhamad', 'last_name' => 'Hamza Alattar', 'email' => 'mhamad-hamza-alattar@approved-users.test', 'phone' => '+963-9110-620-210', 'location' => 'Syria,Damascus', 'job' => 'Full-Stack Web Development', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Mhamad+Hamza+Alattar'],
            // LinkedIn: https://www.linkedin.com/search/results/people/?keywords=Abeer+Al+Otri
            ['slug' => 'abeer-al-otri', 'first_name' => 'Abeer', 'last_name' => 'Al Otri', 'email' => 'abeer-al-otri@approved-users.test', 'phone' => '+963-9112-620-212', 'location' => 'Syria,Damascus', 'job' => 'AI Engineer', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/search/results/people/?keywords=Abeer+Al+Otri'],
            // LinkedIn: https://www.linkedin.com/in/ammar-joukhadar-9855892/
            ['slug' => 'ammar-joukhadar', 'first_name' => 'Ammar', 'last_name' => 'Joukhadar', 'email' => 'ammar-joukhadar@approved-users.test', 'phone' => '+963-9114-620-214', 'location' => 'Syria,Damascus', 'job' => 'Dean of Faculty of IT Engineering, Damascus University', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/ammar-joukhadar-9855892/'],
            // LinkedIn: https://www.linkedin.com/in/abdulrahem-al-zubi/
            ['slug' => 'abdulrahem-al-zoubi', 'first_name' => 'Abdulrahem', 'last_name' => 'Al-Zoubi', 'email' => 'abdulrahem-al-zoubi@approved-users.test', 'phone' => '+963-9116-620-216', 'location' => 'Syria,Damascus', 'job' => 'Full-Stack Engineer; Laravel, NestJS, React and AI SaaS', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/abdulrahem-al-zubi/'],
            // LinkedIn: https://www.linkedin.com/in/mohammed-ali-16057b2b6/
            ['slug' => 'mohammed-ali', 'first_name' => 'Mohammed', 'last_name' => 'Ali', 'email' => 'mohammed-ali@approved-users.test', 'phone' => '+963-9118-620-218', 'location' => 'Syria,Damascus', 'job' => 'ITE student at Damascus University', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/mohammed-ali-16057b2b6/'],
            // LinkedIn: https://www.linkedin.com/in/mohamed-ayman-alkaddour-77aa2b3b6/
            ['slug' => 'mohamed-ayman-alkaddour', 'first_name' => 'Mohamed', 'last_name' => 'Ayman Alkaddour', 'email' => 'mohamed-ayman-alkaddour@approved-users.test', 'phone' => '+963-9120-620-220', 'location' => 'Syria,Damascus', 'job' => 'ITE; C++, Java OOP, Robotics and Problem Solving', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/mohamed-ayman-alkaddour-77aa2b3b6/'],
            // LinkedIn: https://sy.linkedin.com/in/ruba-safsaf-3a31b53a9
            ['slug' => 'ruba-safsaf', 'first_name' => 'Ruba', 'last_name' => 'SafSaf', 'email' => 'ruba-safsaf@approved-users.test', 'phone' => '+963-9122-620-222', 'location' => 'Syria,Damascus', 'job' => 'ITE student at Damascus University', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://sy.linkedin.com/in/ruba-safsaf-3a31b53a9'],
            // LinkedIn: https://sy.linkedin.com/in/msb56/ar
            ['slug' => 'mohamad-samer-bakleh', 'first_name' => 'Mohamad', 'last_name' => 'Samer Bakleh', 'email' => 'mohamad-samer-bakleh@approved-users.test', 'phone' => '+963-9124-620-224', 'location' => 'Syria,Damascus', 'job' => 'Java, Desktop, Backend, DevOps and Cloud', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://sy.linkedin.com/in/msb56/ar'],
            // LinkedIn: https://sy.linkedin.com/in/abdulrahman-el-shehab-062972304
            ['slug' => 'abdulrahman-el-shehab', 'first_name' => 'Abdulrahman', 'last_name' => 'El Shehab', 'email' => 'abdulrahman-el-shehab@approved-users.test', 'phone' => '+963-9126-620-226', 'location' => 'Syria,Damascus', 'job' => 'Information Engineering student and Backend Developer', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://sy.linkedin.com/in/abdulrahman-el-shehab-062972304'],
            // LinkedIn: https://sy.linkedin.com/in/amr-alghafir
            ['slug' => 'amr-alghafir', 'first_name' => 'Amr', 'last_name' => 'ALGhafir', 'email' => 'amr-alghafir@approved-users.test', 'phone' => '+963-9128-620-228', 'location' => 'Syria,Damascus', 'job' => 'AI Engineer; Robotics; Founder at Programmology', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://sy.linkedin.com/in/amr-alghafir'],
            // LinkedIn: https://sy.linkedin.com/in/hala-ramadan-70065a3a9
            ['slug' => 'hala-ramadan', 'first_name' => 'Hala', 'last_name' => 'Ramadan', 'email' => 'hala-ramadan@approved-users.test', 'phone' => '+963-9130-620-230', 'location' => 'Syria,Damascus', 'job' => 'ITE; C++ and Problem Solving', 'gender' => 'female', 'birthday' => '2000-01-01', 'linkedin' => 'https://sy.linkedin.com/in/hala-ramadan-70065a3a9'],
            // LinkedIn: https://sy.linkedin.com/in/ibrahimbz
            ['slug' => 'ibrahim-bazazeh', 'first_name' => 'Ibrahim', 'last_name' => 'Bazazeh', 'email' => 'ibrahim-bazazeh@approved-users.test', 'phone' => '+963-9132-620-232', 'location' => 'Syria,Damascus', 'job' => 'Web Developer and Full-Stack Developer', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://sy.linkedin.com/in/ibrahimbz'],
            // LinkedIn: https://www.linkedin.com/in/bitaranas/
            ['slug' => 'anas-bitar', 'first_name' => 'Anas', 'last_name' => 'Bitar', 'email' => 'anas-bitar@approved-users.test', 'phone' => '+963-9134-620-234', 'location' => 'Syria,Damascus', 'job' => 'ITE; DCPC Finalist and Robotics', 'gender' => 'male', 'birthday' => '2000-01-01', 'linkedin' => 'https://www.linkedin.com/in/bitaranas/'],
        ];
    }
}
